CREATE TABLE IF NOT EXISTS player_skills (
id INT AUTO_INCREMENT PRIMARY KEY,
citizenid VARCHAR(255) NOT NULL,
driving FLOAT DEFAULT 0,
strength FLOAT DEFAULT 0,
diving FLOAT DEFAULT 0,
wheelie_ability FLOAT DEFAULT 0,
stamina FLOAT DEFAULT 0,
shooting FLOAT DEFAULT 0,
